console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("girar a la izquierda");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("Fin ejercicio");
